sudo: false
language: ruby

script: bundle exec ruby spec/unicode_name_spec.rb

rvm:
- 2.6
- 2.5
- 2.4
- 2.3
- 2.2
- 2.1
- 2.0
- ruby-head
- jruby-head
- jruby-9.2.7.0

matrix:
  allow_failures:
    - rvm: 2.3
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0
    - rvm: jruby-head
