sudo: false
language: ruby

script: bundle exec ruby spec/unicode_name_spec.rb

rvm:
- 2.4.0
- 2.3.3
- 2.2
- 2.1
- ruby-head
- jruby-head
- jruby-9.1.7.0

cache:
- bundler

matrix:
  allow_failures:
    - rvm: jruby-head
