sudo: false
language: ruby

script: bundle exec ruby spec/unicode_name_spec.rb

rvm:
- ruby-head
- 2.5.0
- 2.4.3
- 2.3.6
- 2.2
- 2.1
- 2.0
- jruby-head
- jruby-9.1.12.0

matrix:
  allow_failures:
    - rvm: 2.1
    - rvm: 2.0
    - rvm: jruby-head
